# COMANDOS LINUX
con ! podemos acceder a comandos del servidor

In [ ]:
!ls


sample_data


In [ ]:
!pwd

/content


In [ ]:
!pip freeze

In [ ]:
!pip install numpy

# IMPORTAR LIBRERIA

In [2]:
import numpy as np

convirtiendo lista en arrays de numpy

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(lista)

list

In [6]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

slicing

In [8]:
arr[1:4]

array([2, 3, 4])

In [9]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

# tipos de datos en numpy

In [10]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [11]:
arr_float = np.array([1,2,3,4], dtype='float64')
arr_float.dtype

dtype('float64')

In [12]:
arr_float

array([1., 2., 3., 4.])

# cast tipo de dato

In [13]:
arr = np.array([1,2,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [14]:
arr_bool

array([ True,  True,  True,  True])

In [15]:
arr = np.array([1,2,3,4])
arr_string = arr.astype(np.string_)
arr_string

array([b'1', b'2', b'3', b'4'], dtype='|S21')

In [16]:
print(arr_string)

[b'1' b'2' b'3' b'4']
