# COMANDOS LINUX
con ! podemos acceder a comandos del servidor

In [2]:
!ls


sample_data


In [3]:
!pwd

/content


In [ ]:
!pip freeze

In [5]:
!pip install numpy

# IMPORTAR LIBRERIA

In [6]:
import numpy as np

convirtiendo lista en arrays de numpy

In [7]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(lista)

list

In [10]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(arr)

numpy.ndarray

slicing

In [13]:
arr[1:4]

array([2, 3, 4])

In [14]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

# tipos de datos en numpy

In [16]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [18]:
arr_float = np.array([1,2,3,4], dtype='float64')
arr_float.dtype

dtype('float64')

# cast tipo de dato

In [21]:
arr = np.array([1,2,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [22]:
arr_bool

array([ True,  True,  True,  True])

In [24]:
arr = np.array([1,2,3,4])
arr_string = arr.astype(np.string_)
arr_string

array([b'1', b'2', b'3', b'4'], dtype='|S21')