# DIMENSIONES EN NUMPY

In [3]:
import numpy as np

> SCALAR







In [6]:
scalar = np.array(24)
print(scalar)

24


In [7]:
scalar.ndim

0



> vector



In [8]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1



> MATRIZ DE 2 DIMENSIONES



In [11]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2



> tensor



In [14]:
tensor = np.array([[[1,2,3],[4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3