# DATOS ALEATORIOS

In [1]:
import numpy as np



> arange



In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])



> zeros



In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])



> ones



In [6]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])



> EYE





In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])



> linespace



In [9]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])



> random



In [11]:
np.random.rand()

0.9192681318344327

In [12]:
np.random.rand(4)

array([0.85641036, 0.00802675, 0.37178598, 0.22502801])

In [15]:
np.random.rand(4,4)

array([[0.80005564, 0.45662812, 0.90361076, 0.67260269],
       [0.50779672, 0.47417586, 0.95840172, 0.57210101],
       [0.86955044, 0.57445581, 0.47963485, 0.03296665],
       [0.58614399, 0.02628456, 0.98980991, 0.3283277 ]])

In [16]:
np.random.randint(1,100,(10,10))

array([[25, 30, 42, 34, 30, 52, 28, 94, 92, 96],
       [65, 78, 56, 39, 60, 40, 85, 34, 82, 96],
       [44, 93, 94, 94, 62, 25, 79,  2, 93,  4],
       [81, 72, 62, 97,  1, 72, 47, 89, 97, 81],
       [15, 73, 68, 60, 44,  7, 19, 31,  4, 52],
       [42, 32, 51, 48, 21, 45, 45, 54, 94, 17],
       [99, 17,  7, 68, 90, 69, 44, 79, 34, 70],
       [85, 68, 24, 14, 66, 43, 35, 35, 22, 95],
       [28, 85, 13, 42, 58, 39, 91, 61, 79, 75],
       [47, 41, 82, 48, 49, 46, 78, 10, 40, 91]])