# funciones mas comunes en numpy

In [2]:
import numpy as np



> shape y reshape



In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[9, 2],
       [5, 6],
       [9, 4]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [7]:
arr.reshape(1,6)


array([[9, 2, 5, 6, 9, 4]])



> maximos  y argmax



In [9]:
arr = np.random.randint(1,20,10)
arr

array([16,  4, 11,  7, 14, 12, 17,  5,  6, 12])

In [11]:
matriz = arr.reshape(2,5)
matriz

array([[16,  4, 11,  7, 14],
       [12, 17,  5,  6, 12]])

In [12]:
print(matriz)

[[16  4 11  7 14]
 [12 17  5  6 12]]


In [14]:
arr.max()

17

In [15]:
matriz.max()

17

In [16]:
matriz.max(1)

array([16, 17])

In [18]:
matriz.argmax()

6

maximo de cada fila

In [19]:
matriz.argmax(1)

array([0, 1])

maximo de cada columna

In [20]:
matriz.argmax(0)

array([0, 1, 0, 0, 0])



> sort



In [25]:
arr.sort()
arr

array([ 4,  5,  6,  7, 11, 12, 12, 14, 16, 17])



> mediana




In [26]:
np.median(arr)

11.5



> desviacion estandar



In [27]:
np.std(arr)

4.409081537009721