# funciones mas comunes en numpy

In [1]:
import numpy as np



> shape y reshape



In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[3, 4],
       [8, 4],
       [8, 8]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.ndim

2

In [5]:
arr.reshape(1,6)


array([[3, 4, 8, 4, 8, 8]])



> maximos  y argmax



In [6]:
arr = np.random.randint(1,20,10)
arr

array([18, 18,  5,  6,  6, 18,  3, 17, 11, 18])

In [7]:
matriz = arr.reshape(2,5)
matriz

array([[18, 18,  5,  6,  6],
       [18,  3, 17, 11, 18]])

In [8]:
print(matriz)

[[18 18  5  6  6]
 [18  3 17 11 18]]


In [9]:
arr.max()

18

In [10]:
matriz.max()

18

In [11]:
matriz.max(1)

array([18, 18])

In [13]:
matriz.argmax()

0

maximo de cada fila

In [14]:
matriz.argmax(1)

array([0, 0])

maximo de cada columna

In [15]:
matriz.argmax(0)

array([0, 0, 1, 1, 1])



> sort



In [16]:
arr.sort()
arr

array([ 3,  5,  6,  6, 11, 17, 18, 18, 18, 18])



> mediana




In [17]:
np.median(arr)

14.0



> desviacion estandar



In [18]:
np.std(arr)

6.099180272790763