In [1]:
import numpy as np

# FILTROS Y CONDICIONES

In [2]:
array = np.linspace(1,10,10,dtype='int8')
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)



> filtros por condiciones
evalua cada scalar


In [3]:
incide_condiciones = array > 5
incide_condiciones

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
array[incide_condiciones]

array([ 6,  7,  8,  9, 10], dtype=int8)

otra forma de hacerlo es directo en el corchete

In [6]:
array[array < 5]

array([1, 2, 3, 4], dtype=int8)

In [8]:
array[(array < 9) & (array > 5 )]

array([6, 7, 8], dtype=int8)

In [11]:
array[(array < 9) & (array > 5 )] = 99
array

array([ 1,  2,  3,  4,  5, 99, 99, 99,  9, 10], dtype=int8)



> copy como buena practica



In [13]:
array = np.linspace(1,10,10,dtype='int8')
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [15]:
array_copy = array.copy()
array_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)