# OPERACIONES EN NUMPY

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,10)
arr_copy = arr.copy()

print(arr)
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])



> OPERACIONES CON MATRICES



In [10]:
matriz = arr.reshape(2,5)
matriz_2 = matriz.copy()

print(matriz)
print(matriz_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
matriz + matriz_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [13]:
matriz.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])